=== ABCD-DEVCOM/ABCD2/empweb/common/xml/schema/transaction/v1/empweb-transaction-1-0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://kalio.net/empweb/schema/transaction/v1" elementFormDefault="qualified"
    xmlns="http://kalio.net/empweb/schema/transaction/v1"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">

 <!--
  Empweb Transaction Schema. Version 1 / January 2005
  ===================================================

  Description:
  This schema specifies the XML elements that describe a transaction
  pipeline configuration.


  Schema location
  http://kalio.net/empweb/schema/transaction/v1/empweb-transaction-1-0.xsd

  Minimum valid XML example:

  <transaction  name="prestamo" evaluation="shortcut" type="transaction"
                classpath="/trans_rules/classes:/another/path/classes:/yet/another/path/classes"
                xmlns="http://kalio.net/empweb/schema/transaction/v1">
    <environment>
      <param name="env1">env1_val</param>
      <param name="env2">env2_val</param>
    </environment>


    <process name="GetObject" class="net.kalio.empweb.engine.rules.GetObject" enabled="true">
      <doc>This is the documentation for this process</doc>
      <params>
        <param name="mode">copyId</param>
      </params>
    </process>


    <!- - This example shows a custom scripted rule using a fictional EasyXMLInterpreter
          which specifies a bundle for the interpreter's own messages, but the scripts'
          messages are in their own bundle (local.mylibrary), or are of the "raw text" type.
    - ->
    <rule name="MyCustomRule" class="net.mongo.EasyXMLInterpreter" bundle="local.ezxml">
      <limits>
        <limit name="limitedelrule">55</limit>
      </limits>

      <params>
        <param name="script">
          <assertLimit  limit="maxBooks">
            <if cond="gt" value="10">
              <then successful="false">
                <msg>
                  <key bundle="local.mylibrary">too_many_books</key>
                </msg>
              </then>
              <else>            <!- - else's success is opposite of then's - ->
                <text>Cool, you got it!</text>
              </else>
            </if>
          </assertLimit>
        </param>
      </params>
    </rule>


    <finally name="attheend" class="net.mongo.prestamo>
      <params>
        <param name="good">bye</param>
      </params>
    </finally>

  </transaction>

  Copyright 2004-2004 Kalio.Net - Barzilai Spinak - Ciro Mondueri
  All rights reserved
  Barzilai Spinak <barspi@internet.com.uy>
  Ciro Mondueri <ciro@mondueri.com>
  January 2005

-->

  <!-- TRANSACTIONS. A list of transaction pipelines files, with a name and a path. -->
  <xsd:element name="transactions">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="transaction" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="path" type="xsd:string" use="required"/>
            <xsd:attribute name="type" default="transaction" use="optional">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:enumeration value="transaction"/>
                  <xsd:enumeration value="statistic"/>
                  <xsd:enumeration value="configuration"/>
                  <xsd:enumeration value="test"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!-- TRANSACTION. A single transaction pipeline definition. -->
  <xsd:element name="transaction">
    <xsd:complexType>
      <xsd:sequence>

        <!-- the environment is an optional series of global parameters all process/rules can access -->
        <xsd:element ref="environment" minOccurs="0"/>

        <!-- many of these, in any order -->
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
          <xsd:element name="process" type="PRType"/>
          <xsd:element name="rule"    type="PRType"/>
        </xsd:choice>

        <!-- finally tags must occur after processes and rules. They always execute, even if a previous
             one throws an unchecked exception -->
        <xsd:element name="finally" type="PRType" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>

      <!-- transaction element attributes -->
      <xsd:attribute name="name" type="xsd:string" use="required"/>

      <!-- The classpath is a list of paths relative to the "empweb.home" system property.
           The paths are separated by ":" (colon) or ";" semi-colon, indistinctly. -->
      <xsd:attribute name="classpath" type="xsd:string" use="required"/>

      <xsd:attribute name="evaluation" default="full" use="optional">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="shortcut"/>
            <xsd:enumeration value="SHORTCUT"/>
            <xsd:enumeration value="full"/>
            <xsd:enumeration value="FULL"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>

      <!-- The type represents which kind of transaction: an actual transaction,
           a statistic result (can be a list or just a result), or a test -->
      <xsd:attribute name="type" default="transaction" use="optional">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="transaction"/>
            <xsd:enumeration value="statistic"/>
            <xsd:enumeration value="configuration"/>
            <xsd:enumeration value="test"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>

    </xsd:complexType>
  </xsd:element>


  <!-- the environment is an optional series of global parameters all process/rules can access -->
  <xsd:element name="environment">
    <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="param" type="simpleHasNameAttr"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

    <!-- The syntax of a process or rule. -->
  <xsd:complexType name="PRType">
    <xsd:sequence>

      <!-- Try to avoid using XML-style comments for the documentation of a process or rule,
         and use this element instead. This allows automatic tools to extract and manipulate
         the documentation of a transaction pipeline.
      -->
      <xsd:element name="doc" type="xsd:string" minOccurs="0" />

      <!-- If this process/rule uses any limits, they must be declared in this optional
           element. A default value for the limit can be provided here, in case the used
           Profile does not privde one.
      -->
      <xsd:element name="limits" minOccurs="0">
        <xsd:complexType>
          <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="limit" type="simpleHasNameAttr"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <!-- optional parameters to the process/rule -->
      <xsd:element name="params" minOccurs="0">
        <xsd:complexType>
          <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="param" type="simpleHasNameAttr"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>


    <xsd:attribute name="name"    type="xsd:string"   use="required"/>
    <xsd:attribute name="class"   type="xsd:string"   use="required"/>
    <xsd:attribute name="enabled" type="xsd:boolean"  use="optional"/>

    <!-- This instance of the process/rule may(should) specify the i18n bundle
         from which the GUI should resolve its messages. If the process/rule
         does not specify a bundle for the message keys, the Engine will use
         the default for Empweb processes (usually, core.process)
    -->
    <xsd:attribute name="bundle"  type="xsd:string"   use="optional"/>
  </xsd:complexType>



  <!-- auxiliary type to define elements that have a name attribute and simple textual content -->
  <xsd:complexType name="simpleHasNameAttr">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

</xsd:schema>

=== ABCD-DEVCOM/ABCD2/empweb/engine/WEB-INF/conf/stat-pipes/stat-trans-by-ids.xml
<?xml version="1.0" encoding="UTF-8"?>
<transaction classpath="/engine/WEB-INF/trans_rules/classes/" evaluation="shortcut" name="stat-trans-by-ids" type="statistic" xmlns="http://kalio.net/empweb/schema/transaction/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://kalio.net/empweb/schema/transaction/v1                                   ../../../../common/xml/schema/transaction/v1/empweb-transaction-1-0.xsd">
<environment>
    <param name="env1">env1_value</param>
</environment>

<rule class="net.kalio.empweb.engine.rules.GroovyInterpreter" name="PutIdsInTC">
  <params>
    <param name="script">
<![CDATA[
transExtras= tc.get(TransactionContext.TRANSACTION_EXTRAS);
if (transExtras != null)
  {
    tids = transExtras.get("transactionIds");
  }

tc.put("transactionIds", tids);

return true;

]]>
    </param>
  </params>
</rule>

<rule class="net.kalio.empweb.engine.rules.GetTransactionsById" name="GetTransactionsById" />

<rule class="net.kalio.empweb.engine.rules.GroovyInterpreter" name="ListIds">
  <params>
    <param name="script">
<![CDATA[

tl = tc.get("transactionList");

result.append("<transactionList xmlns=\"http://kalio.net/empweb/schema/transactionlist/v1\">");
for (tr in tl)
  {
    result.append(tr.toXMLString());
  }
result.append("</transactionList>");

return true;
]]>
    </param>
  </params>
</rule>
</transaction>

=== ABCD-DEVCOM/ABCD2/empweb/engine/WEB-INF/conf/trans-pipes/fine.xml
<?xml version="1.0" encoding="UTF-8"?>
<transaction classpath="/engine/WEB-INF/trans_rules/classes/" evaluation="shortcut" name="fine" xmlns="http://kalio.net/empweb/schema/transaction/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://kalio.net/empweb/schema/transaction/v1                                  ../../../../common/xml/schema/transaction/v1/empweb-transaction-1-0.xsd">
<environment>
   <!-- <param name="debug">true</param> -->
</environment>

<rule class="net.kalio.empweb.engine.rules.GetUser" name="GetUser"><params>
<!-- checks for expired or disabled user -->
<param name="checkValidity">true</param>
</params></rule>

<rule class="net.kalio.empweb.engine.rules.Lock" name="LockUserStatus">
  <doc>Logical lock of UserStatus</doc>
  <params>
    <param name="timeoutMillis">25000</param>
  </params>
</rule>

<rule class="net.kalio.empweb.engine.rules.GetUserStatus" name="GetUserStatus" />


<process class="net.kalio.empweb.engine.rules.CreateFine" name="CreateFine">
  <doc>Creates a Fine object.
       It may be a manual fine, or a fine related to a late return or expired reservation.
       The behaviour of the Process depends on the existence of a Loan or Reservation in
       the TransacionContext (in which case it will be an object-related Fine), or the
       abscence of both (in which case it will create a manual Fine)
  </doc>
  <params>
    <param name="fineKey">fine</param>
    <param name="manualFineAmountKey">fineAmount</param>
    <param name="manualType">M</param>  <!-- fine type for manual fines -->

    <!-- These two are keys into the transaction extras -->
    <param name="operatorIdExtrasKey">operatorId</param>
    <param name="operatorLocationExtrasKey">operatorLocation</param>
  </params>
</process>


<rule class="net.kalio.empweb.engine.rules.AddTransactionToStatus" name="AddFineToStatus">
  <params>
    <param name="transactionKey">fine</param>
    <param name="toObjectStatus">false</param>
  </params>
</rule>

<process class="net.kalio.empweb.engine.rules.UpdateDb" name="UpdateDb">
  <doc>Updates User/Object Status databases, and stores the Fine to transaction log.</doc>
  <params>
   <param name="transactionKeys">fine</param>
   <param name="storeUserStatus">true</param>
   <param name="storeObjectStatus">false</param>
  </params>
</process>

<process class="net.kalio.empweb.engine.rules.ReturnTransactionResults" name="ReturnTransactionResults">
  <params>
    <param name="resultKeys">fine</param>
  </params>
</process>
<finally class="net.kalio.empweb.engine.rules.Unlock" name="Unlock">
  <doc>Release the logic locks done at the beginning.</doc>
</finally></transaction>

=== ABCD-DEVCOM/ABCD2/empweb/engine/WEB-INF/conf/trans-pipes/cancelsuspension.xml
<?xml version="1.0" encoding="UTF-8"?>
<transaction classpath="/engine/WEB-INF/trans_rules/classes/" evaluation="shortcut" name="cancelsuspension" xmlns="http://kalio.net/empweb/schema/transaction/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://kalio.net/empweb/schema/transaction/v1                                   ../../../../common/xml/schema/transaction/v1/empweb-transaction-1-0.xsd">
<environment>
<!--    <param name="debug">true</param> -->
</environment>
  <rule class="net.kalio.empweb.engine.rules.GetSuspension" name="GetSuspension">
    <doc>Get Suspension from the Empweb DB, using the suspensionId</doc>
    <params>
      <param name="suspensionKey">cancelledSuspension</param>
    </params>
  </rule>

  <rule class="net.kalio.empweb.engine.rules.Lock" name="LockUserStatus">
    <doc>Logical lock of UserStatus</doc>
    <params>
      <param name="timeoutMillis">25000</param>
    </params>
  </rule>

  <rule class="net.kalio.empweb.engine.rules.GetUserStatus" name="GetUserStatus" />


  <rule class="net.kalio.empweb.engine.rules.RemoveTransactionFromStatus" name="RemoveSuspensionFromStatus">
    <params>
      <param name="transactionKey">cancelledSuspension</param>

      <!-- NECESSARY, as an ObjectStatus will not be present in the TransactionContext -->
      <param name="fromObjectStatus">false</param>
    </params>
  </rule>

  <process class="net.kalio.empweb.engine.rules.CreateCancelSuspension" name="CreateCancelSuspension">
    <doc>Creates a suspension cancellation for the given suspension</doc>
    <params>
      <param name="cancelledSuspensionKey">cancelledSuspension</param>
      <param name="cancellationKey">suspensionCancellation</param>
      <param name="operatorLocationExtrasKey">operatorLocation</param>
    </params>
  </process>

  <process class="net.kalio.empweb.engine.rules.UpdateDb" name="UpdateDb">
    <doc>Updates User/Object Status databases, and stores cancellation to transaction log.
    </doc>
    <params>
      <param name="transactionKeys">suspensionCancellation</param>
      <param name="storeUserStatus">true</param>
      <param name="storeObjectStatus">false</param>
    </params>
  </process>

   <process class="net.kalio.empweb.engine.rules.ReturnTransactionResults" name="ReturnTransactionResults">
    <params>
      <param name="resultKeys">suspensionCancellation</param>
    </params>
   </process>

  <finally class="net.kalio.empweb.engine.rules.Unlock" name="Unlock">
    <doc>Release the logic locks done at the beginning.</doc>
  </finally>
</transaction>

=== ABCD-DEVCOM/ABCD2/empweb/engine/WEB-INF/conf/trans-pipes/suspension.xml
<?xml version="1.0" encoding="UTF-8"?>
<transaction classpath="/engine/WEB-INF/trans_rules/classes/" evaluation="shortcut" name="suspension" xmlns="http://kalio.net/empweb/schema/transaction/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://kalio.net/empweb/schema/transaction/v1               ../../../../common/xml/schema/transaction/v1/empweb-transaction-1-0.xsd">
<environment>
 <!--    <param name="debug">true</param> -->
</environment>

<process class="net.kalio.empweb.engine.rules.GetUser" name="GetUser"><params>
<!-- checks for expired or disabled user -->
<param name="checkValidity">true</param>
</params></process>

<rule class="net.kalio.empweb.engine.rules.Lock" name="LockUserStatus">
  <doc>Logical lock of UserStatus</doc>
  <params>
    <param name="timeoutMillis">25000</param>
  </params>
</rule>

<rule class="net.kalio.empweb.engine.rules.GetUserStatus" name="GetUserStatus" />

<process class="net.kalio.empweb.engine.rules.CreateSuspension" name="CreateSuspension">
  <doc>Creates a Suspension object.
       It may be a manual suspension, or a suspension related to a late return or expired reservation.
       The behaviour of the Process depends on the existence of a Loan or Reservation in
       the TransacionContext (in which case it will be an object-related Suspension), or the
       abscence of both (in which case it will create a manual Suspension)
  </doc>
  <limits>
  </limits>
  <params>
    <param name="suspensionKey">suspension</param>
    <param name="manualDaysSuspendedKey">daysSuspended</param>
    <param name="manualType">M</param>  <!-- fine type for manual fines -->

    <!-- considerSkipDays: false(default): compute contiguous days.
                           true: skip the closed-library days (skipDays), giving a total of
                           suspended days possibly greater than the number of contiguous days.
    -->
    <param name="considerSkipDays">true</param>

    <!-- tailSuspensions: false(default). All suspensions are applied starting now, possibly overlapping with
                          other suspensions.
                          true: A new suspension starts after the end date of the latest ending suspension.
    -->
    <param name="tailSuspensions">true</param>

    <!-- These two are keys into the transaction extras -->
    <param name="operatorIdExtrasKey">operatorId</param>
    <param name="operatorLocationExtrasKey">operatorLocation</param>
  </params>
</process>

<rule class="net.kalio.empweb.engine.rules.AddTransactionToStatus" name="AddSuspensionToStatus">
  <params>
    <param name="transactionKey">suspension</param>
    <param name="toObjectStatus">false</param>
  </params>
</rule>


<process class="net.kalio.empweb.engine.rules.UpdateDb" name="UpdateDb">
  <doc>Updates User/Object Status databases, and stores Suspension to transaction log.</doc>
  <params>
   <param name="transactionKeys">suspension</param>
   <param name="storeUserStatus">true</param>
   <param name="storeObjectStatus">false</param>
  </params>
</process>

<process class="net.kalio.empweb.engine.rules.ReturnTransactionResults" name="ReturnTransactionResults">
  <params>
    <param name="resultKeys">suspension</param>
  </params>
</process>
<finally class="net.kalio.empweb.engine.rules.Unlock" name="Unlock">
  <doc>Release the logic locks done at the beginning.</doc>
</finally></transaction>

=== ABCD-DEVCOM/ABCD2/empweb/engine/WEB-INF/conf/trans-pipes/cancelreservation.xml
<?xml version="1.0" encoding="UTF-8"?>
<transaction classpath="/engine/WEB-INF/trans_rules/classes/" evaluation="shortcut" name="cancelreservation" xmlns="http://kalio.net/empweb/schema/transaction/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://kalio.net/empweb/schema/transaction/v1                                   ../../../../common/xml/schema/transaction/v1/empweb-transaction-1-0.xsd">
<environment>
<!-- <param name="debug">true</param> -->
</environment>

  <!-- ====================================================================== -->

  <rule class="net.kalio.empweb.engine.rules.GetReservation" name="GetReservation">
    <doc>Get Reservation DOM from User Status database using the reservationId from the TransactionContext</doc>
    <params>
      <param name="reservationKey">reservation</param>
    </params>
  </rule>

  <rule class="net.kalio.empweb.engine.rules.GetUser" name="GetUser">
    <doc>Get User DOM from (userId, userDb)</doc>
    <params>
      <!-- checks for expired or disabled user -->
      <param name="checkValidity">false</param>
    </params>
  </rule>

  <rule class="net.kalio.empweb.engine.rules.GetObject" name="GetObject">
    <doc>Get Object DOM (mods) from (recordId, objectDb), in recordId mode.</doc>
    <params>
      <param name="mode">recordId</param>
    </params>
  </rule>

  <rule class="net.kalio.empweb.engine.rules.Lock" name="Lock">
    <doc>Logical lock of UserStatus and ObjectStatus</doc>
    <params>
      <param name="timeoutMillis">25000</param>
    </params>
  </rule>

  <rule class="net.kalio.empweb.engine.rules.ExtractUserClass" name="ExtractUserClass">
    <doc>Extract the user class from the user XML and store it in the TransactionContext.</doc>
    <params>
      <!-- If "useDefault" is true, it will return "*" when a user class can't be found -->
      <!--<param name="useDefault">true</param>-->
    </params>
  </rule>

  <rule class="net.kalio.empweb.engine.rules.GetUserStatus" name="GetUserStatus"></rule>
  <rule class="net.kalio.empweb.engine.rules.GetObjectStatus" name="GetObjectStatus"></rule>

  <!-- ====================================================================== -->

  <rule class="net.kalio.empweb.engine.rules.GroovyInterpreter" name="CheckReservationInUserStatus">
    <params>
      <param name="reservationKey">reservation</param>
      <param name="script">
<![CDATA[
// Check if the reservation is in the status, so we dont cancel reservations that were already paid
theReservation = tc.get(tc.getParameter("reservationKey","reservation"))
UserStatus us = tc.get(TransactionContext.USER_STATUS)
if (us.getTransaction(theReservation.getId()) == null)
{
	msg.addText("es","La reserva con ID:${theReservation.getId()} ya fue cancelada.")
        msg.addText("en","The reservation with ID:${theReservation.getId()} was already cancelled.")
    	return false
}
else
  	return true
]]>
      </param>
    </params>
  </rule>

  <!-- ====================================================================== -->

  <process class="net.kalio.empweb.engine.rules.pucv.PublishTimestampAdjustments"  name="PublishTimestampAdjustments">
    <doc>Publica al TC horas de devolucion, de expiracion de reserva, de inicio de reserva, y excepciones
      Obtiene los valores indicados en el pipeline globalenvironment.
    </doc>
    <params/>
  </process>

  <!-- ====================================================================== -->

  <process class="net.kalio.empweb.engine.rules.CreateCancelReservation" name="CreateCancelReservation">
    <params>
      <param name="cancelledReservationKey">reservation</param>
      <param name="cancellationKey">cancelReservation</param>
    </params>
  </process>

  <rule class="net.kalio.empweb.engine.rules.CheckExpiredReservation" name="CheckExpiredReservation">
    <doc>Check whether this reservation is expired and possibly  generate a fine for the user.
    </doc>
    <params>
      <param name="reservationKey">reservation</param>
      <param name="exceptionDaysKey">exceptionDays</param>
      <param name="graceMinutes">15</param>
      <param name="daysOverdueKey">daysOverdue</param>
      <!-- DEBUG  --> <param name="debug">true</param>
    </params>
  </rule>

  <!-- ====================================================================== -->

  <process class="net.kalio.empweb.engine.rules.CreateFine" name="CreateFine">
    <limits>
      <limit name="createFineIfReservationExpired">true</limit> <!-- create a fine if the reservation expired -->
      <limit name="fineAmountIfExpiredNormal">1</limit>         <!-- amount if expired object is not requested -->
      <limit name="fineAmountIfExpiredReserved">2</limit>       <!-- amount if expired object has reservations/waits -->
    </limits>
    <params>
      <param name="fineKey">fine</param>
      <param name="normalType">N</param>   <!-- Type of fine for unrequested late objects -->
      <param name="reservedType">R</param> <!-- Type of fine for requested late objects -->
      <param name="daysOverdueKey">daysOverdue</param>
      <!-- DEBUG --> <param name="debug">true</param>
    </params>
  </process>

  <process class="net.kalio.empweb.engine.rules.CreateSuspension" name="CreateSuspension">
    <limits>
      <limit name="createSuspensionIfReservationExpired">true</limit>  <!-- create a suspension if the reservation expired -->
      <limit name="suspensionDaysIfExpiredNormal">2</limit>            <!-- suspension days if expired  object is not requested -->
      <limit name="suspensionDaysIfExpiredReserved">3</limit>          <!-- suspension days if expired object is not requested -->
    </limits>
    <params>
      <!-- are suspension days multiplied? (suspensionDaysNormal*overdue = suspensionDays) -->
      <param name="suspensionDaysMultiply">false</param>
    </params>
  </process>

  <!-- ====================================================================== -->

  <rule class="net.kalio.empweb.engine.rules.RemoveTransactionFromStatus" name="RemoveReservationFromStatus">
    <params>
      <param name="transactionKey">reservation</param>
    </params>
  </rule>


  <rule class="net.kalio.empweb.engine.rules.AddTransactionToStatus" name="AddFineToStatus">
    <params>
      <param name="transactionKey">fine</param>
      <param name="toObjectStatus">false</param>
      <!-- DEBUG --> <param name="debug">true</param>

    </params>
  </rule>

  <rule class="net.kalio.empweb.engine.rules.AddTransactionToStatus" name="AddSuspensionToStatus">
     <params>
      <param name="transactionKey">suspension</param>
      <param name="toObjectStatus">false</param>
      <!-- DEBUG --> <param name="debug">true</param>

    </params>
  </rule>


  <process class="net.kalio.empweb.engine.rules.UpdateDb"  name="UpdateDb">
    <doc>Updates User/Object Status databases, and stores the cancelled reservation to the transaction log.</doc>
    <params>
      <param name="transactionKeys">suspension,fine,cancelReservation</param>
      <param name="ignoreTransactionNotFound">true</param>
      <param name="storeUserStatus">false</param>
      <param name="storeObjectStatus">true</param>
    </params>
  </process>

  <!-- ====================================================================== -->

  <process class="net.kalio.empweb.engine.rules.ReturnTransactionResults" name="ReturnTransactionResults">
  <params>
    <param name="resultKeys">suspension, fine, cancelReservation</param>
  </params>
</process>

  <!-- ======================== FINALLY SECTION ====================== -->

  <finally class="net.kalio.empweb.engine.rules.Unlock" name="Unlock">
    <doc>Release the logic locks done at the beginning.</doc>
  </finally>

</transaction>
